version: '3.8'

services:
  app:
    build:
      context: ./app
    environment:
      - API_KEY=${API_KEY}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ericona
      POSTGRES_PASSWORD: ericona
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
