version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: Extract_weather_app
    ports:
      - "1000:1000"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
    command: ["python", "app.py"]  # Adjust command to run your Flask app

  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ericona
      POSTGRES_DB: meteo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
